  services:
    schemesaathi-agent:
      build: 
          context: .
          dockerfile: Dockerfile
      restart: unless-stopped
      env_file: .env 
      networks:
        - schemesaathi-network  

    schemesaathi-app:
      build: 
          context: ../app
          dockerfile: Dockerfile
      restart: unless-stopped
      networks:
        - schemesaathi-network     

    reverse-proxy:
      image: caddy:latest
      container_name: caddy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
        - ./origin.pem:/etc/caddy/origin.pem:ro
        - ./origin.key:/etc/caddy/origin.key:ro
      restart: unless-stopped  
      depends_on:
        - schemesaathi-agent
        - schemesaathi-app
      networks:
        - schemesaathi-network


  networks:
    schemesaathi-network:
      driver: bridge


