  services:
    schemesaathi-agent:
      build: 
          context: .
          dockerfile: Dockerfile
      restart: unless-stopped
      env_file: .env 
      networks:
        - schemesaathi-network   

    reverse-proxy:
      image: caddy:latest
      container_name: caddy
      ports:
        - "80:80"
        - "443:443"
      volumes:
        - ./Caddyfile:/etc/caddy/Caddyfile:ro
      depends_on:
        - schemesaathi-agent
      networks:
        - schemesaathi-network


  networks:
    schemesaathi-network:
      driver: bridge


